version: '2'
services:

    haproxy:
      image: 'dockercloud/haproxy:latest'
      links:
        - app
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - EXTRA_GLOBAL_SETTINGS=debug  

    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password

    app:
      build: .
      ports:
        - 4001
      environment:
        - DB_USER=admin
        - DB_PASSWORD=password
        - DB_HOSTNAME=postgres
      depends_on:
        - postgres
      links:
        - postgres
