version: '3'
services:

    postgres:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password

    app:
      build: .
      ports:
        - "4001:4001"
      environment:
        - DB_USER=admin
        - DB_PASSWORD=password
        - DB_HOSTNAME=postgres
      depends_on:
        - postgres
      links:
        - postgres
